output:
  format: github-actions,checkstyle:golangci-lint-report.json
linters:
  enable:
    - errcheck
    - gosec
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused